let number = 10;
let price = 20.5;
let status = true;
let city = "Hà Nội";
document.write(number);
document.write("<br>");
document.write(price);
document.write("<br>");
document.write(status);
document.write("<br>");
document.write(city);
